service: organizationAPI

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

functions:
  organization:
    handler: dist/handler.organization 
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
    PORT:3001
    MONGO_URI:MONGO_URI:Mondo URL
